package it.solvingteam.padelmanagement.model.slot;

public enum SlotName {
	OTTO,
	OTTO_E_TRENTA,
	NOVE,
	NOVE_E_TRENTA,
	DIECI,
	DIECI_E_TRENTA,
    UNDICI,
	UNDICI_E_TRENTA,
	DODICI,
	DODICI_E_TRENTA,
	TREDICI,
	TREDICI_E_TRENTA,
	QUATTORDICI,
	QUATTORDICI_E_TRENTA,
	QUINDICI,
	QUINDICI_E_TRENTA,
	SEDICI,
	SEDICI_E_TRENTA,
	DICIASSETTE,
	DICIASSETTE_E_TRENTA,
	DICIOTTO,
	DICIOTTO_E_TRENTA,
	DICIANNOVE,
	DICIANNOVE_E_TRENTA,
	VENTI,
	VENTI_E_TRENTA,
	VENTUNO,
	VENTUNO_E_TRENTA,
	VENTIDUE;

}
